version: '3.8'

services:
  odoo_db:
    image: postgres:15
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo_app:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    environment:
      HOST: odoo_db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
